.\" See man groff_mdoc for template and other information.
.\"
.\" Copyright (C) (2011-2021) Battelle Memorial Institute.
.\"
.Dd January 10, 2009
.Os Linux/Windows XP
.Dt FLOWER 5 FLOWER
.Sh NAME
.Nm flower.conf
.Nd flower(8) configuration file.
.Sh DESCRIPTION
.Nm
will read network packets from an input file containing packets in libpcap format or from a network interface device and write network flow records to files in the output directory.
.Sh EXAMPLES
.Cm
.Nm
-i=eth0 -d=/data/flower
.Pp
Reads network packets from eth0 and writes network flow records to files in /data/flower.
.Sh CONFIGURATION
 #
 #  NOTE: After saving any changes run the following as root:
 #        service flower restart
 #
 
 #  Name of site where data is collected
 site-name                   = pnnl_dev
 
 #
 #  Configure output file and directories
 #
 #  The output data directory where all output files will be created
 output-data-dir             = /data/flower
 #  The file extention to add to output data files
 output-file-ext             = dat
 #  The output files will be owned by this group (from /etc/group)
 output-file-group           = root
   
 #
 #  Set Performance and limits
 #
 #  The packet header capture length in bytes (passed to libpcap)
 snaplen                     = 65535
 #  The maximum time (in seconds) to keep idle flows in the cache
 cache-timeout               = 120
 #  The time (in seconds) to force flows from the cache
 cache-forceout              = 900
 #  The time (in seconds) to force summaries to output files
 summary-forceout            = 900
 #  The maximum number of flows allowed in the flow cache
 max-flowcache-size          = 200000
  
 # 
 #  Packet capture settings 
 # 
 #  Capture packets during unexpected termination  
 #    value is 0 for off or 1 for on 
 buffer-packets              = 1 
 #  Maximum number of packet to buffer in case of unexpected termination 
 max-packetbuffer-size       = 10000
 #  Use the Linux Packet Ring (bypass libpcap)
 use-ring                    = 1
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It Ev N/A
.Sh SEE ALSO
.Xr flower 8
.Bl -tag -width Fl
.Sh HISTORY
First availability January 2009.
.Sh AUTHORS
FLOWER TEAM (flower-support@pnnl.gov) Battelle Pacific Northwest Laboratory
.Sh BUGS
None have been identified
