
//
//  DEVELOPER NOTE: This file was generated by generate_test_packets.pl
//


#ifndef PACKETS_HPP
#define PACKETS_HPP


#include <map>
#include <string>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/date_time/posix_time/time_formatters.hpp>
#include "EventTypes.hpp"
#include "utility.hpp"
#include "packets/Pair.hpp"


using namespace std;
using namespace boost::posix_time;


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IPV6_ICMPV6.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-12-02 13:22:12.845213 ::                    ff02::1:ff00:2        ICMPv6   Neighbor solicitation
Frame 1 (78 bytes on wire, 78 bytes captured)
    Arrival Time: Dec  2, 2008 13:22:12.845213000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 78 bytes
    Capture Length: 78 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ipv6:icmpv6]
    [Coloring Rule Name: Broadcast]
    [Coloring Rule String: eth[0] & 1]
Ethernet II, Src: Vmware_94:10:61 (00:50:56:94:10:61), Dst: IPv6mcast_ff:00:00:02 (33:33:ff:00:00:02)
    Destination: IPv6mcast_ff:00:00:02 (33:33:ff:00:00:02)
        Address: IPv6mcast_ff:00:00:02 (33:33:ff:00:00:02)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
    Source: Vmware_94:10:61 (00:50:56:94:10:61)
        Address: Vmware_94:10:61 (00:50:56:94:10:61)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IPv6 (0x86dd)
Internet Protocol Version 6
    0110 .... = Version: 6
        [0110 .... = This field makes the filter "ip.version == 6" possible: 6]
    .... 0000 0000 .... .... .... .... .... = Traffic class: 0x00000000
    .... .... .... 0000 0000 0000 0000 0000 = Flowlabel: 0x00000000
    Payload length: 24
    Next header: ICMPv6 (0x3a)
    Hop limit: 255
    Source: :: (::)
    Destination: ff02::1:ff00:2 (ff02::1:ff00:2)
Internet Control Message Protocol v6
    Type: 135 (Neighbor solicitation)
    Code: 0
    Checksum: 0x54a4 [correct]
    Target: 2600::2
######################################################################
*/
#endif

string get_IPV6_ICMPV6_str(void)
{
  string IPV6_ICMPV6_str = "0,site-name,1228224132.845213,0.000000,,58,,,0000:0000:0000:0000:0000:0000:0000:0000,ff02:0000:0000:0000:0000:0001:ff00:0002,16,,78,,1,,,,,,8700,,+8700,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(IPV6_ICMPV6_str);
}


sharedPacket get_IPV6_ICMPV6_pkt(void)
{
  string ts("2008-12-02 13:22:12.845213");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[78] = 
  {
    0x33, 0x33, 0xff, 0x00, 0x00, 0x02, 0x00, 0x50, 
    0x56, 0x94, 0x10, 0x61, 0x86, 0xdd, 0x60, 0x00,
    0x00, 0x00, 0x00, 0x18, 0x3a, 0xff, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x02, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0xff, 0x00, 0x00, 0x02, 0x87, 0x00, 
    0x54, 0xa4, 0x00, 0x00, 0x00, 0x00, 0x26, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x02
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 78;
  packet_header.len        = 78;
  packet_header.ts.tv_sec  = 1228224132;
  packet_header.ts.tv_usec = 845213;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IPV6_TCP_HTTP_truncated.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
     18 2008-12-03 12:49:58.416903 2600::2               2600::1               HTTP     GET /welcome.png HTTP/ [Packet size limited during capture]
Frame 18 (337 bytes on wire, 96 bytes captured)
    Arrival Time: Dec  3, 2008 12:49:58.416903000
    [Time delta from previous captured frame: 0.006877000 seconds]
    [Time delta from previous displayed frame: 0.006877000 seconds]
    [Time since reference or first frame: 14.776240000 seconds]
    Frame Number: 18
    Frame Length: 337 bytes
    Capture Length: 96 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ipv6:tcp:http]
    [Coloring Rule Name: HTTP]
    [Coloring Rule String: http || tcp.port == 80]
Ethernet II, Src: Vmware_94:10:61 (00:50:56:94:10:61), Dst: Vmware_94:72:02 (00:50:56:94:72:02)
    Destination: Vmware_94:72:02 (00:50:56:94:72:02)
        Address: Vmware_94:72:02 (00:50:56:94:72:02)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: Vmware_94:10:61 (00:50:56:94:10:61)
        Address: Vmware_94:10:61 (00:50:56:94:10:61)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IPv6 (0x86dd)
Internet Protocol Version 6
    0110 .... = Version: 6
        [0110 .... = This field makes the filter "ip.version == 6" possible: 6]
    .... 0000 0000 .... .... .... .... .... = Traffic class: 0x00000000
    .... .... .... 0000 0000 0000 0000 0000 = Flowlabel: 0x00000000
    Payload length: 283
    Next header: TCP (0x06)
    Hop limit: 128
    Source: 2600::2 (2600::2)
    Destination: 2600::1 (2600::1)
Transmission Control Protocol, Src Port: danf-ak2 (1041), Dst Port: http (80), Seq: 3377865330, Ack: 1848700553, Len: 263
    Source port: danf-ak2 (1041)
    Destination port: http (80)
    Sequence number: 3377865330
    [Next sequence number: 3377865593]
    Acknowledgement number: 1848700553
    Header length: 20 bytes
    Flags: 0x18 (PSH, ACK)
        0... .... = Congestion Window Reduced (CWR): Not set
        .0.. .... = ECN-Echo: Not set
        ..0. .... = Urgent: Not set
        ...1 .... = Acknowledgment: Set
        .... 1... = Push: Set
        .... .0.. = Reset: Not set
        .... ..0. = Syn: Not set
        .... ...0 = Fin: Not set
    Window size: 16324
    Checksum: 0xdf0e [unchecked, not all data available]
        [Good Checksum: False]
        [Bad Checksum: False]
    [SEQ/ACK analysis]
        [This is an ACK to the segment in frame: 17]
        [The RTT to ACK the segment was: 0.006877000 seconds]
Hypertext Transfer Protocol
    GET /welcome.png HTTP/
        Request Method: GET
        Request URI: /welcome.png
        Request Version: HTTP/
[Packet size limited during capture: HTTP truncated]
######################################################################
*/
#endif

string get_IPV6_TCP_HTTP_truncated_str(void)
{
  string IPV6_TCP_HTTP_truncated_str = "0,site-name,1228308598.416903,0.000000,,6,,,2600:0000:0000:0000:0000:0000:0000:0002,2600:0000:0000:0000:0000:0000:0000:0001,22,,96,,1,,,,1041,80,,,,,,18,,+18,,3377865330,,,,3377865330,,,,,,,,,,,,,C,,00002000";

  return(IPV6_TCP_HTTP_truncated_str);
}


sharedPacket get_IPV6_TCP_HTTP_truncated_pkt(void)
{
  string ts("2008-12-03 12:49:58.416903");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[96] = 
  {
    0x00, 0x50, 0x56, 0x94, 0x72, 0x02, 0x00, 0x50, 
    0x56, 0x94, 0x10, 0x61, 0x86, 0xdd, 0x60, 0x00,
    0x00, 0x00, 0x01, 0x1b, 0x06, 0x80, 0x26, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x26, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x04, 0x11, 
    0x00, 0x50, 0xc9, 0x56, 0x22, 0x72, 0x6e, 0x30,
    0xee, 0x89, 0x50, 0x18, 0x3f, 0xc4, 0xdf, 0x0e, 
    0x00, 0x00, 0x47, 0x45, 0x54, 0x20, 0x2f, 0x77,
    0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 
    0x6e, 0x67, 0x20, 0x48, 0x54, 0x54, 0x50, 0x2f
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 96;
  packet_header.len        = 96;
  packet_header.ts.tv_sec  = 1228308598;
  packet_header.ts.tv_usec = 416903;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IPV6_UDP_truncated.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
    405 2008-12-02 13:23:15.390561 fe80::75da:69a1:6392:e687 ff02::c               UDP      Source port: 57443  Destination port: ws-discovery
Frame 405 (1053 bytes on wire, 96 bytes captured)
    Arrival Time: Dec  2, 2008 13:23:15.390561000
    [Time delta from previous captured frame: 0.034703000 seconds]
    [Time delta from previous displayed frame: 0.034703000 seconds]
    [Time since reference or first frame: 106.230653000 seconds]
    Frame Number: 405
    Frame Length: 1053 bytes
    Capture Length: 96 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ipv6:udp:data]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: Vmware_94:4b:29 (00:50:56:94:4b:29), Dst: IPv6mcast_00:00:00:0c (33:33:00:00:00:0c)
    Destination: IPv6mcast_00:00:00:0c (33:33:00:00:00:0c)
        Address: IPv6mcast_00:00:00:0c (33:33:00:00:00:0c)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
    Source: Vmware_94:4b:29 (00:50:56:94:4b:29)
        Address: Vmware_94:4b:29 (00:50:56:94:4b:29)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IPv6 (0x86dd)
Internet Protocol Version 6
    0110 .... = Version: 6
        [0110 .... = This field makes the filter "ip.version == 6" possible: 6]
    .... 0000 0000 .... .... .... .... .... = Traffic class: 0x00000000
    .... .... .... 0000 0000 0000 0000 0000 = Flowlabel: 0x00000000
    Payload length: 999
    Next header: UDP (0x11)
    Hop limit: 1
    Source: fe80::75da:69a1:6392:e687 (fe80::75da:69a1:6392:e687)
    Destination: ff02::c (ff02::c)
User Datagram Protocol, Src Port: 57443 (57443), Dst Port: ws-discovery (3702)
    Source port: 57443 (57443)
    Destination port: ws-discovery (3702)
    Length: 999
    Checksum: 0xbc34
        [Good Checksum: False]
        [Bad Checksum: False]
Data (34 bytes)
    Data: 3C3F786D6C2076657273696F6E3D22312E302220656E636F...
######################################################################
*/
#endif

string get_IPV6_UDP_truncated_str(void)
{
  string IPV6_UDP_truncated_str = "0,site-name,1228224195.390561,0.000000,,17,,,fe80:0000:0000:0000:75da:69a1:6392:e687,ff02:0000:0000:0000:0000:0000:0000:000c,34,,96,,1,,,,57443,3702,,,,,,,,,,,,,,,,,,,,,,,,,,,C,,00002000";

  return(IPV6_UDP_truncated_str);
}


sharedPacket get_IPV6_UDP_truncated_pkt(void)
{
  string ts("2008-12-02 13:23:15.390561");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[96] = 
  {
    0x33, 0x33, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x50, 
    0x56, 0x94, 0x4b, 0x29, 0x86, 0xdd, 0x60, 0x00,
    0x00, 0x00, 0x03, 0xe7, 0x11, 0x01, 0xfe, 0x80, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x75, 0xda,
    0x69, 0xa1, 0x63, 0x92, 0xe6, 0x87, 0xff, 0x02, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0xe0, 0x63, 
    0x0e, 0x76, 0x03, 0xe7, 0xbc, 0x34, 0x3c, 0x3f,
    0x78, 0x6d, 0x6c, 0x20, 0x76, 0x65, 0x72, 0x73, 
    0x69, 0x6f, 0x6e, 0x3d, 0x22, 0x31, 0x2e, 0x30,
    0x22, 0x20, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 
    0x6e, 0x67, 0x3d, 0x22, 0x75, 0x74, 0x66, 0x2d
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 96;
  packet_header.len        = 96;
  packet_header.ts.tv_sec  = 1228224195;
  packet_header.ts.tv_usec = 390561;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IP_ICMP_UDP_unreachable.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:09:25.114948 140.221.223.251       202.99.11.99          ICMP     Destination unreachable (Port unreachable)
Frame 1 (70 bytes on wire, 70 bytes captured)
    Arrival Time: Nov  9, 2008 22:09:25.114948000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 70 bytes
    Capture Length: 70 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ip:icmp:ip:udp]
    [Coloring Rule Name: ICMP errors]
    [Coloring Rule String: icmp.type eq 3 || icmp.type eq 4 || icmp.type eq 5 || icmp.type eq 11]
Ethernet II, Src: JuniperN_92:48:bc (00:1d:b5:92:48:bc), Dst: Cisco_8a:64:00 (00:11:5d:8a:64:00)
    Destination: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        Address: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        Address: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.223.251 (140.221.223.251), Dst: 202.99.11.99 (202.99.11.99)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0xc0 (DSCP 0x30: Class Selector 6; ECN: 0x00)
        1100 00.. = Differentiated Services Codepoint: Class Selector 6 (0x30)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 56
    Identification: 0x3ee6 (16102)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 252
    Protocol: ICMP (0x01)
    Header checksum: 0x3c7f [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.223.251 (140.221.223.251)
    Destination: 202.99.11.99 (202.99.11.99)
Internet Control Message Protocol
    Type: 3 (Destination unreachable)
    Code: 3 (Port unreachable)
    Checksum: 0x0337 [correct]
    Internet Protocol, Src: 202.99.11.99 (202.99.11.99), Dst: 140.221.223.251 (140.221.223.251)
        Version: 4
        Header length: 20 bytes
        Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
            0000 00.. = Differentiated Services Codepoint: Default (0x00)
            .... ..0. = ECN-Capable Transport (ECT): 0
            .... ...0 = ECN-CE: 0
        Total Length: 404
        Identification: 0xc462 (50274)
        Flags: 0x00
            0... = Reserved bit: Not set
            .0.. = Don't fragment: Not set
            ..0. = More fragments: Not set
        Fragment offset: 0
        Time to live: 111
        Protocol: UDP (0x11)
        Header checksum: 0x4357 [correct]
            [Good: True]
            [Bad : False]
        Source: 202.99.11.99 (202.99.11.99)
        Destination: 140.221.223.251 (140.221.223.251)
    User Datagram Protocol, Src Port: menandmice-lpm (1231), Dst Port: ms-sql-m (1434)
        Source port: menandmice-lpm (1231)
        Destination port: ms-sql-m (1434)
        Length: 384
        Checksum: 0xeddc
            [Good Checksum: False]
            [Bad Checksum: False]
######################################################################
*/
#endif

string get_IP_ICMP_UDP_unreachable_str(void)
{
  string IP_ICMP_UDP_unreachable_str = "0,site-name,1226268565.114948,0.000000,,1,140.221.223.251,202.99.11.99,,,28,,70,,1,,,,,,0303,,+0303,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(IP_ICMP_UDP_unreachable_str);
}


sharedPacket get_IP_ICMP_UDP_unreachable_pkt(void)
{
  string ts("2008-11-09 22:09:25.114948");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[70] = 
  {
    0x00, 0x11, 0x5d, 0x8a, 0x64, 0x00, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0xbc, 0x08, 0x00, 0x45, 0xc0,
    0x00, 0x38, 0x3e, 0xe6, 0x00, 0x00, 0xfc, 0x01, 
    0x3c, 0x7f, 0x8c, 0xdd, 0xdf, 0xfb, 0xca, 0x63,
    0x0b, 0x63, 0x03, 0x03, 0x03, 0x37, 0x00, 0x00, 
    0x00, 0x00, 0x45, 0x00, 0x01, 0x94, 0xc4, 0x62,
    0x00, 0x00, 0x6f, 0x11, 0x43, 0x57, 0xca, 0x63, 
    0x0b, 0x63, 0x8c, 0xdd, 0xdf, 0xfb, 0x04, 0xcf,
    0x05, 0x9a, 0x01, 0x80, 0xed, 0xdc
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 70;
  packet_header.len        = 70;
  packet_header.ts.tv_sec  = 1226268565;
  packet_header.ts.tv_usec = 114948;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IP_ICMP_ping.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:08:21.682943 66.114.52.24          140.221.251.250       ICMP     Echo (ping) request
Frame 1 (60 bytes on wire, 60 bytes captured)
    Arrival Time: Nov  9, 2008 22:08:21.682943000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 60 bytes
    Capture Length: 60 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ip:icmp:data]
    [Coloring Rule Name: ICMP]
    [Coloring Rule String: icmp]
Ethernet II, Src: Cisco_8a:64:00 (00:11:5d:8a:64:00), Dst: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
    Destination: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        Address: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        Address: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IP (0x0800)
    Trailer: 000000000000000000000000000000000000
Internet Protocol, Src: 66.114.52.24 (66.114.52.24), Dst: 140.221.251.250 (140.221.251.250)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 28
    Identification: 0x1a54 (6740)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 23
    Protocol: ICMP (0x01)
    Header checksum: 0x8a2b [correct]
        [Good: True]
        [Bad : False]
    Source: 66.114.52.24 (66.114.52.24)
    Destination: 140.221.251.250 (140.221.251.250)
Internet Control Message Protocol
    Type: 8 (Echo (ping) request)
    Code: 0 ()
    Checksum: 0xddab [correct]
    Identifier: 0x1a54
    Sequence number: 0 (0x0000)
######################################################################
*/
#endif

string get_IP_ICMP_ping_str(void)
{
  string IP_ICMP_ping_str = "0,site-name,1226268501.682943,0.000000,,1,66.114.52.24,140.221.251.250,,,,,42,,1,,,,,,0800,,+0800,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(IP_ICMP_ping_str);
}


sharedPacket get_IP_ICMP_ping_pkt(void)
{
  string ts("2008-11-09 22:08:21.682943");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[60] = 
  {
    0x00, 0x1d, 0xb5, 0x92, 0x48, 0xbc, 0x00, 0x11, 
    0x5d, 0x8a, 0x64, 0x00, 0x08, 0x00, 0x45, 0x00,
    0x00, 0x1c, 0x1a, 0x54, 0x00, 0x00, 0x17, 0x01, 
    0x8a, 0x2b, 0x42, 0x72, 0x34, 0x18, 0x8c, 0xdd,
    0xfb, 0xfa, 0x08, 0x00, 0xdd, 0xab, 0x1a, 0x54, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 60;
  packet_header.len        = 60;
  packet_header.ts.tv_sec  = 1226268501;
  packet_header.ts.tv_usec = 682943;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IP_IGMP.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:05:52.424181 4.71.171.98           224.0.0.1             IGMP     V2 Membership Query, general
Frame 1 (60 bytes on wire, 60 bytes captured)
    Arrival Time: Nov  9, 2008 22:05:52.424181000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 60 bytes
    Capture Length: 60 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ip:igmp]
    [Coloring Rule Name: Routing]
    [Coloring Rule String: hsrp || eigrp || ospf || bgp || cdp || vrrp || gvrp || igmp || ismp]
Ethernet II, Src: JuniperN_92:48:bc (00:1d:b5:92:48:bc), Dst: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
    Destination: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
        Address: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        Address: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IP (0x0800)
    Trailer: 0000000000000000000000000000
Internet Protocol, Src: 4.71.171.98 (4.71.171.98), Dst: 224.0.0.1 (224.0.0.1)
    Version: 4
    Header length: 24 bytes
    Differentiated Services Field: 0xc0 (DSCP 0x30: Class Selector 6; ECN: 0x00)
        1100 00.. = Differentiated Services Codepoint: Class Selector 6 (0x30)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 32
    Identification: 0xf024 (61476)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 1
    Protocol: IGMP (0x02)
    Header checksum: 0xa448 [correct]
        [Good: True]
        [Bad : False]
    Source: 4.71.171.98 (4.71.171.98)
    Destination: 224.0.0.1 (224.0.0.1)
    Options: (4 bytes)
        Router Alert: Every router examines packet
Internet Group Management Protocol
    IGMP Version: 2
    Type: Membership Query (0x11)
    Max Response Time: 10.0 sec (0x64)
    Header checksum: 0xee9b [correct]
    Multicast Address: 0.0.0.0 (0.0.0.0)
######################################################################
*/
#endif

string get_IP_IGMP_str(void)
{
  string IP_IGMP_str = "0,site-name,1226268352.424181,0.000000,,2,4.71.171.98,224.0.0.1,,,8,,46,,1,,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(IP_IGMP_str);
}


sharedPacket get_IP_IGMP_pkt(void)
{
  string ts("2008-11-09 22:05:52.424181");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[60] = 
  {
    0x01, 0x00, 0x5e, 0x00, 0x00, 0x01, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0xbc, 0x08, 0x00, 0x46, 0xc0,
    0x00, 0x20, 0xf0, 0x24, 0x00, 0x00, 0x01, 0x02, 
    0xa4, 0x48, 0x04, 0x47, 0xab, 0x62, 0xe0, 0x00,
    0x00, 0x01, 0x94, 0x04, 0x00, 0x00, 0x11, 0x64, 
    0xee, 0x9b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 60;
  packet_header.len        = 60;
  packet_header.ts.tv_sec  = 1226268352;
  packet_header.ts.tv_usec = 424181;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IP_TCP_HTTP.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
   5596 2008-11-09 22:04:56.151550 140.221.238.250       208.43.48.106         HTTP     GET /?action=messages&a=get&userid=10591667&key=8ac308cf6e74c7baef67aad03705378c0a963b3a&m=1491d6df-7fac-4f1a-96f8-eea03f7e3a86&g=d2ddbdee-bfa9-4815-9a10-06201bced89b&toolid=56891 HTTP/1.1 
Frame 5596 (993 bytes on wire, 993 bytes captured)
    Arrival Time: Nov  9, 2008 22:04:56.151550000
    [Time delta from previous captured frame: 0.001498000 seconds]
    [Time delta from previous displayed frame: 0.001498000 seconds]
    [Time since reference or first frame: 40.114371000 seconds]
    Frame Number: 5596
    Frame Length: 993 bytes
    Capture Length: 993 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ip:tcp:http]
    [Coloring Rule Name: HTTP]
    [Coloring Rule String: http || tcp.port == 80]
Ethernet II, Src: JuniperN_92:48:bc (00:1d:b5:92:48:bc), Dst: Cisco_8a:64:00 (00:11:5d:8a:64:00)
    Destination: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        Address: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        Address: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.238.250 (140.221.238.250), Dst: 208.43.48.106 (208.43.48.106)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 979
    Identification: 0x7034 (28724)
    Flags: 0x04 (Don't Fragment)
        0... = Reserved bit: Not set
        .1.. = Don't fragment: Set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 126
    Protocol: TCP (0x06)
    Header checksum: 0x0c83 [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.238.250 (140.221.238.250)
    Destination: 208.43.48.106 (208.43.48.106)
Transmission Control Protocol, Src Port: prsvp (3455), Dst Port: http (80), Seq: 511129658, Ack: 4050514875, Len: 939
    Source port: prsvp (3455)
    Destination port: http (80)
    Sequence number: 511129658
    [Next sequence number: 511130597]
    Acknowledgement number: 4050514875
    Header length: 20 bytes
    Flags: 0x18 (PSH, ACK)
        0... .... = Congestion Window Reduced (CWR): Not set
        .0.. .... = ECN-Echo: Not set
        ..0. .... = Urgent: Not set
        ...1 .... = Acknowledgment: Set
        .... 1... = Push: Set
        .... .0.. = Reset: Not set
        .... ..0. = Syn: Not set
        .... ...0 = Fin: Not set
    Window size: 17520
    Checksum: 0xf3cf [correct]
        [Good Checksum: True]
        [Bad Checksum: False]
Hypertext Transfer Protocol
    GET /?action=messages&a=get&userid=10591667&key=8ac308cf6e74c7baef67aad03705378c0a963b3a&m=1491d6df-7fac-4f1a-96f8-eea03f7e3a86&g=d2ddbdee-bfa9-4815-9a10-06201bced89b&toolid=56891 HTTP/1.1\r\n
        Request Method: GET
        Request URI: /?action=messages&a=get&userid=10591667&key=8ac308cf6e74c7baef67aad03705378c0a963b3a&m=1491d6df-7fac-4f1a-96f8-eea03f7e3a86&g=d2ddbdee-bfa9-4815-9a10-06201bced89b&toolid=56891
        Request Version: HTTP/1.1
    Host: xml.freecause.com\r\n
    User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3\r\n
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*;q=0.8\r\n
    Accept-Language: en-us,en;q=0.5\r\n
    ---------------: ------------\r\n
    Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\n
    Keep-Alive: 300\r\n
    Connection: keep-alive\r\n
    [truncated] Cookie: toolbar_read_messages_56891=; toolbar_deleted_messages_56891=1107%2C1197; freecause_user_56891=10591667; freecause_key_56891=8ac308cf6e74c7baef67aad03705378c0a963b3a; SESSc7b2fb4c6d6005d1a0722ea0d599e00a=2gm6rloia9c1rd2
    \r\n
######################################################################
*/
#endif

string get_IP_TCP_HTTP_str(void)
{
  string IP_TCP_HTTP_str = "0,site-name,1226268296.151550,0.000000,,6,140.221.238.250,208.43.48.106,,,939,,993,,1,,,,3455,80,,,,,,18,,+18,,511129658,,,,511129658,,,,,,,,,,,,,C,,";

  return(IP_TCP_HTTP_str);
}


sharedPacket get_IP_TCP_HTTP_pkt(void)
{
  string ts("2008-11-09 22:04:56.151550");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[993] = 
  {
    0x00, 0x11, 0x5d, 0x8a, 0x64, 0x00, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0xbc, 0x08, 0x00, 0x45, 0x00,
    0x03, 0xd3, 0x70, 0x34, 0x40, 0x00, 0x7e, 0x06, 
    0x0c, 0x83, 0x8c, 0xdd, 0xee, 0xfa, 0xd0, 0x2b,
    0x30, 0x6a, 0x0d, 0x7f, 0x00, 0x50, 0x1e, 0x77, 
    0x38, 0x3a, 0xf1, 0x6d, 0xf3, 0xbb, 0x50, 0x18,
    0x44, 0x70, 0xf3, 0xcf, 0x00, 0x00, 0x47, 0x45, 
    0x54, 0x20, 0x2f, 0x3f, 0x61, 0x63, 0x74, 0x69,
    0x6f, 0x6e, 0x3d, 0x6d, 0x65, 0x73, 0x73, 0x61, 
    0x67, 0x65, 0x73, 0x26, 0x61, 0x3d, 0x67, 0x65,
    0x74, 0x26, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 
    0x3d, 0x31, 0x30, 0x35, 0x39, 0x31, 0x36, 0x36,
    0x37, 0x26, 0x6b, 0x65, 0x79, 0x3d, 0x38, 0x61, 
    0x63, 0x33, 0x30, 0x38, 0x63, 0x66, 0x36, 0x65,
    0x37, 0x34, 0x63, 0x37, 0x62, 0x61, 0x65, 0x66, 
    0x36, 0x37, 0x61, 0x61, 0x64, 0x30, 0x33, 0x37,
    0x30, 0x35, 0x33, 0x37, 0x38, 0x63, 0x30, 0x61, 
    0x39, 0x36, 0x33, 0x62, 0x33, 0x61, 0x26, 0x6d,
    0x3d, 0x31, 0x34, 0x39, 0x31, 0x64, 0x36, 0x64, 
    0x66, 0x2d, 0x37, 0x66, 0x61, 0x63, 0x2d, 0x34,
    0x66, 0x31, 0x61, 0x2d, 0x39, 0x36, 0x66, 0x38, 
    0x2d, 0x65, 0x65, 0x61, 0x30, 0x33, 0x66, 0x37,
    0x65, 0x33, 0x61, 0x38, 0x36, 0x26, 0x67, 0x3d, 
    0x64, 0x32, 0x64, 0x64, 0x62, 0x64, 0x65, 0x65,
    0x2d, 0x62, 0x66, 0x61, 0x39, 0x2d, 0x34, 0x38, 
    0x31, 0x35, 0x2d, 0x39, 0x61, 0x31, 0x30, 0x2d,
    0x30, 0x36, 0x32, 0x30, 0x31, 0x62, 0x63, 0x65, 
    0x64, 0x38, 0x39, 0x62, 0x26, 0x74, 0x6f, 0x6f,
    0x6c, 0x69, 0x64, 0x3d, 0x35, 0x36, 0x38, 0x39, 
    0x31, 0x20, 0x48, 0x54, 0x54, 0x50, 0x2f, 0x31,
    0x2e, 0x31, 0x0d, 0x0a, 0x48, 0x6f, 0x73, 0x74, 
    0x3a, 0x20, 0x78, 0x6d, 0x6c, 0x2e, 0x66, 0x72,
    0x65, 0x65, 0x63, 0x61, 0x75, 0x73, 0x65, 0x2e, 
    0x63, 0x6f, 0x6d, 0x0d, 0x0a, 0x55, 0x73, 0x65,
    0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 
    0x20, 0x4d, 0x6f, 0x7a, 0x69, 0x6c, 0x6c, 0x61,
    0x2f, 0x35, 0x2e, 0x30, 0x20, 0x28, 0x57, 0x69, 
    0x6e, 0x64, 0x6f, 0x77, 0x73, 0x3b, 0x20, 0x55,
    0x3b, 0x20, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 
    0x73, 0x20, 0x4e, 0x54, 0x20, 0x35, 0x2e, 0x31,
    0x3b, 0x20, 0x65, 0x6e, 0x2d, 0x55, 0x53, 0x3b, 
    0x20, 0x72, 0x76, 0x3a, 0x31, 0x2e, 0x39, 0x2e,
    0x30, 0x2e, 0x33, 0x29, 0x20, 0x47, 0x65, 0x63, 
    0x6b, 0x6f, 0x2f, 0x32, 0x30, 0x30, 0x38, 0x30,
    0x39, 0x32, 0x34, 0x31, 0x37, 0x20, 0x46, 0x69, 
    0x72, 0x65, 0x66, 0x6f, 0x78, 0x2f, 0x33, 0x2e,
    0x30, 0x2e, 0x33, 0x0d, 0x0a, 0x41, 0x63, 0x63, 
    0x65, 0x70, 0x74, 0x3a, 0x20, 0x74, 0x65, 0x78,
    0x74, 0x2f, 0x68, 0x74, 0x6d, 0x6c, 0x2c, 0x61, 
    0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
    0x6f, 0x6e, 0x2f, 0x78, 0x68, 0x74, 0x6d, 0x6c, 
    0x2b, 0x78, 0x6d, 0x6c, 0x2c, 0x61, 0x70, 0x70,
    0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 
    0x2f, 0x78, 0x6d, 0x6c, 0x3b, 0x71, 0x3d, 0x30,
    0x2e, 0x39, 0x2c, 0x2a, 0x2f, 0x2a, 0x3b, 0x71, 
    0x3d, 0x30, 0x2e, 0x38, 0x0d, 0x0a, 0x41, 0x63,
    0x63, 0x65, 0x70, 0x74, 0x2d, 0x4c, 0x61, 0x6e, 
    0x67, 0x75, 0x61, 0x67, 0x65, 0x3a, 0x20, 0x65,
    0x6e, 0x2d, 0x75, 0x73, 0x2c, 0x65, 0x6e, 0x3b, 
    0x71, 0x3d, 0x30, 0x2e, 0x35, 0x0d, 0x0a, 0x2d,
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x3a, 0x20,
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 
    0x2d, 0x2d, 0x2d, 0x2d, 0x0d, 0x0a, 0x41, 0x63,
    0x63, 0x65, 0x70, 0x74, 0x2d, 0x43, 0x68, 0x61, 
    0x72, 0x73, 0x65, 0x74, 0x3a, 0x20, 0x49, 0x53,
    0x4f, 0x2d, 0x38, 0x38, 0x35, 0x39, 0x2d, 0x31, 
    0x2c, 0x75, 0x74, 0x66, 0x2d, 0x38, 0x3b, 0x71,
    0x3d, 0x30, 0x2e, 0x37, 0x2c, 0x2a, 0x3b, 0x71, 
    0x3d, 0x30, 0x2e, 0x37, 0x0d, 0x0a, 0x4b, 0x65,
    0x65, 0x70, 0x2d, 0x41, 0x6c, 0x69, 0x76, 0x65, 
    0x3a, 0x20, 0x33, 0x30, 0x30, 0x0d, 0x0a, 0x43,
    0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 
    0x6e, 0x3a, 0x20, 0x6b, 0x65, 0x65, 0x70, 0x2d,
    0x61, 0x6c, 0x69, 0x76, 0x65, 0x0d, 0x0a, 0x43, 
    0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x3a, 0x20, 0x74,
    0x6f, 0x6f, 0x6c, 0x62, 0x61, 0x72, 0x5f, 0x72, 
    0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73,
    0x61, 0x67, 0x65, 0x73, 0x5f, 0x35, 0x36, 0x38, 
    0x39, 0x31, 0x3d, 0x3b, 0x20, 0x74, 0x6f, 0x6f,
    0x6c, 0x62, 0x61, 0x72, 0x5f, 0x64, 0x65, 0x6c, 
    0x65, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73,
    0x73, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x35, 0x36, 
    0x38, 0x39, 0x31, 0x3d, 0x31, 0x31, 0x30, 0x37,
    0x25, 0x32, 0x43, 0x31, 0x31, 0x39, 0x37, 0x3b, 
    0x20, 0x66, 0x72, 0x65, 0x65, 0x63, 0x61, 0x75,
    0x73, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 
    0x35, 0x36, 0x38, 0x39, 0x31, 0x3d, 0x31, 0x30,
    0x35, 0x39, 0x31, 0x36, 0x36, 0x37, 0x3b, 0x20, 
    0x66, 0x72, 0x65, 0x65, 0x63, 0x61, 0x75, 0x73,
    0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x35, 0x36, 
    0x38, 0x39, 0x31, 0x3d, 0x38, 0x61, 0x63, 0x33,
    0x30, 0x38, 0x63, 0x66, 0x36, 0x65, 0x37, 0x34, 
    0x63, 0x37, 0x62, 0x61, 0x65, 0x66, 0x36, 0x37,
    0x61, 0x61, 0x64, 0x30, 0x33, 0x37, 0x30, 0x35, 
    0x33, 0x37, 0x38, 0x63, 0x30, 0x61, 0x39, 0x36,
    0x33, 0x62, 0x33, 0x61, 0x3b, 0x20, 0x53, 0x45, 
    0x53, 0x53, 0x63, 0x37, 0x62, 0x32, 0x66, 0x62,
    0x34, 0x63, 0x36, 0x64, 0x36, 0x30, 0x30, 0x35, 
    0x64, 0x31, 0x61, 0x30, 0x37, 0x32, 0x32, 0x65,
    0x61, 0x30, 0x64, 0x35, 0x39, 0x39, 0x65, 0x30, 
    0x30, 0x61, 0x3d, 0x32, 0x67, 0x6d, 0x36, 0x72,
    0x6c, 0x6f, 0x69, 0x61, 0x39, 0x63, 0x31, 0x72, 
    0x64, 0x32, 0x38, 0x73, 0x35, 0x69, 0x63, 0x70,
    0x66, 0x67, 0x6d, 0x71, 0x30, 0x3b, 0x20, 0x5f, 
    0x5f, 0x75, 0x74, 0x6d, 0x61, 0x3d, 0x32, 0x32,
    0x32, 0x35, 0x32, 0x38, 0x33, 0x33, 0x32, 0x2e, 
    0x32, 0x38, 0x33, 0x39, 0x30, 0x33, 0x38, 0x32,
    0x37, 0x36, 0x31, 0x34, 0x32, 0x33, 0x32, 0x39, 
    0x30, 0x30, 0x30, 0x2e, 0x31, 0x32, 0x32, 0x36,
    0x31, 0x34, 0x30, 0x37, 0x30, 0x39, 0x2e, 0x31, 
    0x32, 0x32, 0x36, 0x31, 0x34, 0x30, 0x37, 0x30,
    0x39, 0x2e, 0x31, 0x32, 0x32, 0x36, 0x31, 0x34, 
    0x30, 0x37, 0x30, 0x39, 0x2e, 0x31, 0x3b, 0x20,
    0x5f, 0x5f, 0x75, 0x74, 0x6d, 0x7a, 0x3d, 0x32, 
    0x32, 0x32, 0x35, 0x32, 0x38, 0x33, 0x33, 0x32,
    0x2e, 0x31, 0x32, 0x32, 0x36, 0x31, 0x34, 0x30, 
    0x37, 0x30, 0x39, 0x2e, 0x31, 0x2e, 0x31, 0x2e,
    0x75, 0x74, 0x6d, 0x63, 0x73, 0x72, 0x3d, 0x28, 
    0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x29, 0x7c,
    0x75, 0x74, 0x6d, 0x63, 0x63, 0x6e, 0x3d, 0x28, 
    0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x29, 0x7c,
    0x75, 0x74, 0x6d, 0x63, 0x6d, 0x64, 0x3d, 0x28, 
    0x6e, 0x6f, 0x6e, 0x65, 0x29, 0x0d, 0x0a, 0x0d,
    0x0a
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 993;
  packet_header.len        = 993;
  packet_header.ts.tv_sec  = 1226268296;
  packet_header.ts.tv_usec = 151550;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      IP_UDP_DNS.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
  33078 2008-11-09 22:08:21.053798 140.221.251.250       192.12.94.30          DNS      Standard query A beacon.securestudies.com
Frame 33078 (95 bytes on wire, 95 bytes captured)
    Arrival Time: Nov  9, 2008 22:08:21.053798000
    [Time delta from previous captured frame: 0.063399000 seconds]
    [Time delta from previous displayed frame: 0.377049000 seconds]
    [Time since reference or first frame: 245.016619000 seconds]
    Frame Number: 33078
    Frame Length: 95 bytes
    Capture Length: 95 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:ip:udp:dns]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: JuniperN_92:48:bc (00:1d:b5:92:48:bc), Dst: Cisco_8a:64:00 (00:11:5d:8a:64:00)
    Destination: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        Address: Cisco_8a:64:00 (00:11:5d:8a:64:00)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        Address: JuniperN_92:48:bc (00:1d:b5:92:48:bc)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.251.250 (140.221.251.250), Dst: 192.12.94.30 (192.12.94.30)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 81
    Identification: 0xf680 (63104)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 62
    Protocol: UDP (0x11)
    Header checksum: 0xdf18 [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.251.250 (140.221.251.250)
    Destination: 192.12.94.30 (192.12.94.30)
User Datagram Protocol, Src Port: 48506 (48506), Dst Port: domain (53)
    Source port: 48506 (48506)
    Destination port: domain (53)
    Length: 61
    Checksum: 0x58b5 [correct]
        [Good Checksum: True]
        [Bad Checksum: False]
Domain Name System (query)
    [Response In: 33116]
    Transaction ID: 0xfc45
    Flags: 0x0000 (Standard query)
        0... .... .... .... = Response: Message is a query
        .000 0... .... .... = Opcode: Standard query (0)
        .... ..0. .... .... = Truncated: Message is not truncated
        .... ...0 .... .... = Recursion desired: Don't do query recursively
        .... .... .0.. .... = Z: reserved (0)
        .... .... ...0 .... = Non-authenticated data OK: Non-authenticated data is unacceptable
    Questions: 1
    Answer RRs: 0
    Authority RRs: 0
    Additional RRs: 1
    Queries
        beacon.securestudies.com: type A, class IN
            Name: beacon.securestudies.com
            Type: A (Host address)
            Class: IN (0x0001)
    Additional records
        <Root>: type OPT
            Name: <Root>
            Type: OPT (EDNS0 option)
            UDP payload size: 4096
            Higher bits in extended RCODE: 0x0
            EDNS0 version: 0
            Z: 0x8000
                Bit 0 (DO bit): 1 (Accepts DNSSEC security RRs)
                Bits 1-15: 0x0 (reserved)
            Data length: 0
######################################################################
*/
#endif

string get_IP_UDP_DNS_str(void)
{
  string IP_UDP_DNS_str = "0,site-name,1226268501.053798,0.000000,,17,140.221.251.250,192.12.94.30,,,53,,95,,1,,,,48506,53,,,,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(IP_UDP_DNS_str);
}


sharedPacket get_IP_UDP_DNS_pkt(void)
{
  string ts("2008-11-09 22:08:21.053798");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[95] = 
  {
    0x00, 0x11, 0x5d, 0x8a, 0x64, 0x00, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0xbc, 0x08, 0x00, 0x45, 0x00,
    0x00, 0x51, 0xf6, 0x80, 0x00, 0x00, 0x3e, 0x11, 
    0xdf, 0x18, 0x8c, 0xdd, 0xfb, 0xfa, 0xc0, 0x0c,
    0x5e, 0x1e, 0xbd, 0x7a, 0x00, 0x35, 0x00, 0x3d, 
    0x58, 0xb5, 0xfc, 0x45, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x06, 0x62, 
    0x65, 0x61, 0x63, 0x6f, 0x6e, 0x0d, 0x73, 0x65,
    0x63, 0x75, 0x72, 0x65, 0x73, 0x74, 0x75, 0x64, 
    0x69, 0x65, 0x73, 0x03, 0x63, 0x6f, 0x6d, 0x00,
    0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x29, 0x10, 
    0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 95;
  packet_header.len        = 95;
  packet_header.ts.tv_sec  = 1226268501;
  packet_header.ts.tv_usec = 53798;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      VLAN_IP_ICMP_UDP_unreachable.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:05:31.533850 140.221.251.18        220.191.255.66        ICMP     Destination unreachable (Port unreachable)
Frame 1 (74 bytes on wire, 74 bytes captured)
    Arrival Time: Nov  9, 2008 22:05:31.533850000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 74 bytes
    Capture Length: 74 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:vlan:ip:icmp:ip:udp]
    [Coloring Rule Name: ICMP errors]
    [Coloring Rule String: icmp.type eq 3 || icmp.type eq 4 || icmp.type eq 5 || icmp.type eq 11]
Ethernet II, Src: JuniperN_92:48:7e (00:1d:b5:92:48:7e), Dst: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
    Destination: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        Address: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        Address: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 0, CFI: 0, ID: 521
    000. .... .... .... = Priority: 0
    ...0 .... .... .... = CFI: 0
    .... 0010 0000 1001 = ID: 521
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.251.18 (140.221.251.18), Dst: 220.191.255.66 (220.191.255.66)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 56
    Identification: 0x18e0 (6368)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 254
    Protocol: ICMP (0x01)
    Header checksum: 0x3ff2 [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.251.18 (140.221.251.18)
    Destination: 220.191.255.66 (220.191.255.66)
Internet Control Message Protocol
    Type: 3 (Destination unreachable)
    Code: 3 (Port unreachable)
    Checksum: 0x24b9 [correct]
    Internet Protocol, Src: 220.191.255.66 (220.191.255.66), Dst: 140.221.251.65 (140.221.251.65)
        Version: 4
        Header length: 20 bytes
        Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
            0000 00.. = Differentiated Services Codepoint: Default (0x00)
            .... ..0. = ECN-Capable Transport (ECT): 0
            .... ...0 = ECN-CE: 0
        Total Length: 404
        Identification: 0x9881 (39041)
        Flags: 0x00
            0... = Reserved bit: Not set
            .0.. = Don't fragment: Not set
            ..0. = More fragments: Not set
        Fragment offset: 0
        Time to live: 115
        Protocol: UDP (0x11)
        Header checksum: 0x49b6 [correct]
            [Good: True]
            [Bad : False]
        Source: 220.191.255.66 (220.191.255.66)
        Destination: 140.221.251.65 (140.221.251.65)
    User Datagram Protocol, Src Port: 54120 (54120), Dst Port: ms-sql-m (1434)
        Source port: 54120 (54120)
        Destination port: ms-sql-m (1434)
        Length: 384
        Checksum: 0xfdc0
            [Good Checksum: False]
            [Bad Checksum: False]
######################################################################
*/
#endif

string get_VLAN_IP_ICMP_UDP_unreachable_str(void)
{
  string VLAN_IP_ICMP_UDP_unreachable_str = "0,site-name,1226268331.533850,0.000000,521,1,140.221.251.18,220.191.255.66,,,28,,74,,1,,,,,,0303,,+0303,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(VLAN_IP_ICMP_UDP_unreachable_str);
}


sharedPacket get_VLAN_IP_ICMP_UDP_unreachable_pkt(void)
{
  string ts("2008-11-09 22:05:31.533850");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[74] = 
  {
    0x00, 0x90, 0x69, 0x75, 0xe4, 0x9d, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0x7e, 0x81, 0x00, 0x02, 0x09,
    0x08, 0x00, 0x45, 0x00, 0x00, 0x38, 0x18, 0xe0, 
    0x00, 0x00, 0xfe, 0x01, 0x3f, 0xf2, 0x8c, 0xdd,
    0xfb, 0x12, 0xdc, 0xbf, 0xff, 0x42, 0x03, 0x03, 
    0x24, 0xb9, 0x00, 0x00, 0x00, 0x00, 0x45, 0x00,
    0x01, 0x94, 0x98, 0x81, 0x00, 0x00, 0x73, 0x11, 
    0x49, 0xb6, 0xdc, 0xbf, 0xff, 0x42, 0x8c, 0xdd,
    0xfb, 0x41, 0xd3, 0x68, 0x05, 0x9a, 0x01, 0x80, 
    0xfd, 0xc0
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 74;
  packet_header.len        = 74;
  packet_header.ts.tv_sec  = 1226268331;
  packet_header.ts.tv_usec = 533850;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      VLAN_IP_ICMP_ping.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:05:19.316919 204.56.255.74         140.221.248.55        ICMP     Echo (ping) request
Frame 1 (66 bytes on wire, 66 bytes captured)
    Arrival Time: Nov  9, 2008 22:05:19.316919000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 66 bytes
    Capture Length: 66 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:vlan:ip:icmp:data]
    [Coloring Rule Name: ICMP]
    [Coloring Rule String: icmp]
Ethernet II, Src: JuniperN_92:48:7e (00:1d:b5:92:48:7e), Dst: Fiberlan_d3:e6:f2 (00:10:cf:d3:e6:f2)
    Destination: Fiberlan_d3:e6:f2 (00:10:cf:d3:e6:f2)
        Address: Fiberlan_d3:e6:f2 (00:10:cf:d3:e6:f2)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        Address: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 0, CFI: 0, ID: 170
    000. .... .... .... = Priority: 0
    ...0 .... .... .... = CFI: 0
    .... 0000 1010 1010 = ID: 170
    Type: IP (0x0800)
Internet Protocol, Src: 204.56.255.74 (204.56.255.74), Dst: 140.221.248.55 (140.221.248.55)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 48
    Identification: 0xe889 (59529)
    Flags: 0x04 (Don't Fragment)
        0... = Reserved bit: Not set
        .1.. = Don't fragment: Set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 247
    Protocol: ICMP (0x01)
    Header checksum: 0x4aaa [correct]
        [Good: True]
        [Bad : False]
    Source: 204.56.255.74 (204.56.255.74)
    Destination: 140.221.248.55 (140.221.248.55)
Internet Control Message Protocol
    Type: 8 (Echo (ping) request)
    Code: 0 ()
    Checksum: 0x0d27 [correct]
    Identifier: 0xd4e0
    Sequence number: 28687 (0x700f)
    Data (20 bytes)
        Data: 694D21724831B7914917CF1F0004B0CE2E382424
######################################################################
*/
#endif

string get_VLAN_IP_ICMP_ping_str(void)
{
  string VLAN_IP_ICMP_ping_str = "0,site-name,1226268319.316919,0.000000,170,1,204.56.255.74,140.221.248.55,,,20,,66,,1,,,,,,0800,,+0800,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(VLAN_IP_ICMP_ping_str);
}


sharedPacket get_VLAN_IP_ICMP_ping_pkt(void)
{
  string ts("2008-11-09 22:05:19.316919");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[66] = 
  {
    0x00, 0x10, 0xcf, 0xd3, 0xe6, 0xf2, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0x7e, 0x81, 0x00, 0x00, 0xaa,
    0x08, 0x00, 0x45, 0x00, 0x00, 0x30, 0xe8, 0x89, 
    0x40, 0x00, 0xf7, 0x01, 0x4a, 0xaa, 0xcc, 0x38,
    0xff, 0x4a, 0x8c, 0xdd, 0xf8, 0x37, 0x08, 0x00, 
    0x0d, 0x27, 0xd4, 0xe0, 0x70, 0x0f, 0x69, 0x4d,
    0x21, 0x72, 0x48, 0x31, 0xb7, 0x91, 0x49, 0x17, 
    0xcf, 0x1f, 0x00, 0x04, 0xb0, 0xce, 0x2e, 0x38,
    0x24, 0x24
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 66;
  packet_header.len        = 66;
  packet_header.ts.tv_sec  = 1226268319;
  packet_header.ts.tv_usec = 316919;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      VLAN_IP_IGMP.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
      1 2008-11-09 22:04:36.128060 192.124.226.98        224.0.0.1             IGMP     V2 Membership Query, general
Frame 1 (64 bytes on wire, 64 bytes captured)
    Arrival Time: Nov  9, 2008 22:04:36.128060000
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 64 bytes
    Capture Length: 64 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:vlan:ip:igmp]
    [Coloring Rule Name: Routing]
    [Coloring Rule String: hsrp || eigrp || ospf || bgp || cdp || vrrp || gvrp || igmp || ismp]
Ethernet II, Src: JuniperN_92:48:7e (00:1d:b5:92:48:7e), Dst: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
    Destination: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
        Address: IPv4mcast_00:00:01 (01:00:5e:00:00:01)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        Address: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 6, CFI: 0, ID: 521
    110. .... .... .... = Priority: 6
    ...0 .... .... .... = CFI: 0
    .... 0010 0000 1001 = ID: 521
    Type: IP (0x0800)
    Trailer: 0000000000000000000000000000
Internet Protocol, Src: 192.124.226.98 (192.124.226.98), Dst: 224.0.0.1 (224.0.0.1)
    Version: 4
    Header length: 24 bytes
    Differentiated Services Field: 0xc0 (DSCP 0x30: Class Selector 6; ECN: 0x00)
        1100 00.. = Differentiated Services Codepoint: Class Selector 6 (0x30)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 32
    Identification: 0xed18 (60696)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 1
    Protocol: IGMP (0x02)
    Header checksum: 0xb41e [correct]
        [Good: True]
        [Bad : False]
    Source: 192.124.226.98 (192.124.226.98)
    Destination: 224.0.0.1 (224.0.0.1)
    Options: (4 bytes)
        Router Alert: Every router examines packet
Internet Group Management Protocol
    IGMP Version: 2
    Type: Membership Query (0x11)
    Max Response Time: 10.0 sec (0x64)
    Header checksum: 0xee9b [correct]
    Multicast Address: 0.0.0.0 (0.0.0.0)
######################################################################
*/
#endif

string get_VLAN_IP_IGMP_str(void)
{
  string VLAN_IP_IGMP_str = "0,site-name,1226268276.128060,0.000000,521,2,192.124.226.98,224.0.0.1,,,8,,50,,1,,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(VLAN_IP_IGMP_str);
}


sharedPacket get_VLAN_IP_IGMP_pkt(void)
{
  string ts("2008-11-09 22:04:36.128060");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[64] = 
  {
    0x01, 0x00, 0x5e, 0x00, 0x00, 0x01, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0x7e, 0x81, 0x00, 0xc2, 0x09,
    0x08, 0x00, 0x46, 0xc0, 0x00, 0x20, 0xed, 0x18, 
    0x00, 0x00, 0x01, 0x02, 0xb4, 0x1e, 0xc0, 0x7c,
    0xe2, 0x62, 0xe0, 0x00, 0x00, 0x01, 0x94, 0x04, 
    0x00, 0x00, 0x11, 0x64, 0xee, 0x9b, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 64;
  packet_header.len        = 64;
  packet_header.ts.tv_sec  = 1226268276;
  packet_header.ts.tv_usec = 128060;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      VLAN_IP_TCP_HTTP.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
   6358 2008-11-09 22:04:59.772389 140.221.238.250       192.124.226.41        HTTP     GET /Splash/Videos/1108_uhp_tpain.jpg HTTP/1.1 
Frame 6358 (839 bytes on wire, 839 bytes captured)
    Arrival Time: Nov  9, 2008 22:04:59.772389000
    [Time delta from previous captured frame: 0.000539000 seconds]
    [Time delta from previous displayed frame: 0.717495000 seconds]
    [Time since reference or first frame: 43.735210000 seconds]
    Frame Number: 6358
    Frame Length: 839 bytes
    Capture Length: 839 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:vlan:ip:tcp:http]
    [Coloring Rule Name: HTTP]
    [Coloring Rule String: http || tcp.port == 80]
Ethernet II, Src: JuniperN_92:48:7e (00:1d:b5:92:48:7e), Dst: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
    Destination: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        Address: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        Address: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 0, CFI: 0, ID: 521
    000. .... .... .... = Priority: 0
    ...0 .... .... .... = CFI: 0
    .... 0010 0000 1001 = ID: 521
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.238.250 (140.221.238.250), Dst: 192.124.226.41 (192.124.226.41)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 821
    Identification: 0x73e9 (29673)
    Flags: 0x04 (Don't Fragment)
        0... = Reserved bit: Not set
        .1.. = Don't fragment: Set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 126
    Protocol: TCP (0x06)
    Header checksum: 0x675b [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.238.250 (140.221.238.250)
    Destination: 192.124.226.41 (192.124.226.41)
Transmission Control Protocol, Src Port: ipether232port (3497), Dst Port: http (80), Seq: 4211522027, Ack: 4085709350, Len: 781
    Source port: ipether232port (3497)
    Destination port: http (80)
    Sequence number: 4211522027
    [Next sequence number: 4211522808]
    Acknowledgement number: 4085709350
    Header length: 20 bytes
    Flags: 0x18 (PSH, ACK)
        0... .... = Congestion Window Reduced (CWR): Not set
        .0.. .... = ECN-Echo: Not set
        ..0. .... = Urgent: Not set
        ...1 .... = Acknowledgment: Set
        .... 1... = Push: Set
        .... .0.. = Reset: Not set
        .... ..0. = Syn: Not set
        .... ...0 = Fin: Not set
    Window size: 17520
    Checksum: 0x687d [correct]
        [Good Checksum: True]
        [Bad Checksum: False]
Hypertext Transfer Protocol
    GET /Splash/Videos/1108_uhp_tpain.jpg HTTP/1.1\r\n
        Request Method: GET
        Request URI: /Splash/Videos/1108_uhp_tpain.jpg
        Request Version: HTTP/1.1
    Host: cms.myspacecdn.com\r\n
    User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3\r\n
    Accept: image/png,image;q=0.8,*;q=0.5\r\n
    Accept-Language: en-us,en;q=0.5\r\n
    ---------------: ------------\r\n
    Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\n
    Keep-Alive: 300\r\n
    Connection: keep-alive\r\n
    Referer: http://home.myspace.com/index.cfm?fuseaction=user\r\n
    [truncated] Cookie: MSCulture=IP=140.221.238.250&IPCulture=en-US&PreferredCulture=en-US&PreferredCulturePending=&Country=VVM=&ForcedExpiration=0&timeZone=0&USRLOC=QXJlYUNvZGU9NjMwJkNpdHk9TGVtb250JkNvdW50cnlDb2RlPVVTJkNvdW50cnlOYW1lPVVuaXRl
    \r\n
######################################################################
*/
#endif

string get_VLAN_IP_TCP_HTTP_str(void)
{
  string VLAN_IP_TCP_HTTP_str = "0,site-name,1226268299.772389,0.000000,521,6,140.221.238.250,192.124.226.41,,,781,,839,,1,,,,3497,80,,,,,,18,,+18,,4211522027,,,,4211522027,,,,,,,,,,,,,C,,";

  return(VLAN_IP_TCP_HTTP_str);
}


sharedPacket get_VLAN_IP_TCP_HTTP_pkt(void)
{
  string ts("2008-11-09 22:04:59.772389");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[839] = 
  {
    0x00, 0x90, 0x69, 0x75, 0xe4, 0x9d, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0x7e, 0x81, 0x00, 0x02, 0x09,
    0x08, 0x00, 0x45, 0x00, 0x03, 0x35, 0x73, 0xe9, 
    0x40, 0x00, 0x7e, 0x06, 0x67, 0x5b, 0x8c, 0xdd,
    0xee, 0xfa, 0xc0, 0x7c, 0xe2, 0x29, 0x0d, 0xa9, 
    0x00, 0x50, 0xfb, 0x06, 0xb9, 0xeb, 0xf3, 0x86,
    0xfa, 0x26, 0x50, 0x18, 0x44, 0x70, 0x68, 0x7d, 
    0x00, 0x00, 0x47, 0x45, 0x54, 0x20, 0x2f, 0x53,
    0x70, 0x6c, 0x61, 0x73, 0x68, 0x2f, 0x56, 0x69, 
    0x64, 0x65, 0x6f, 0x73, 0x2f, 0x31, 0x31, 0x30,
    0x38, 0x5f, 0x75, 0x68, 0x70, 0x5f, 0x74, 0x70, 
    0x61, 0x69, 0x6e, 0x2e, 0x6a, 0x70, 0x67, 0x20,
    0x48, 0x54, 0x54, 0x50, 0x2f, 0x31, 0x2e, 0x31, 
    0x0d, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20,
    0x63, 0x6d, 0x73, 0x2e, 0x6d, 0x79, 0x73, 0x70, 
    0x61, 0x63, 0x65, 0x63, 0x64, 0x6e, 0x2e, 0x63,
    0x6f, 0x6d, 0x0d, 0x0a, 0x55, 0x73, 0x65, 0x72, 
    0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20,
    0x4d, 0x6f, 0x7a, 0x69, 0x6c, 0x6c, 0x61, 0x2f, 
    0x35, 0x2e, 0x30, 0x20, 0x28, 0x57, 0x69, 0x6e,
    0x64, 0x6f, 0x77, 0x73, 0x3b, 0x20, 0x55, 0x3b, 
    0x20, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73,
    0x20, 0x4e, 0x54, 0x20, 0x35, 0x2e, 0x31, 0x3b, 
    0x20, 0x65, 0x6e, 0x2d, 0x55, 0x53, 0x3b, 0x20,
    0x72, 0x76, 0x3a, 0x31, 0x2e, 0x39, 0x2e, 0x30, 
    0x2e, 0x33, 0x29, 0x20, 0x47, 0x65, 0x63, 0x6b,
    0x6f, 0x2f, 0x32, 0x30, 0x30, 0x38, 0x30, 0x39, 
    0x32, 0x34, 0x31, 0x37, 0x20, 0x46, 0x69, 0x72,
    0x65, 0x66, 0x6f, 0x78, 0x2f, 0x33, 0x2e, 0x30, 
    0x2e, 0x33, 0x0d, 0x0a, 0x41, 0x63, 0x63, 0x65,
    0x70, 0x74, 0x3a, 0x20, 0x69, 0x6d, 0x61, 0x67, 
    0x65, 0x2f, 0x70, 0x6e, 0x67, 0x2c, 0x69, 0x6d,
    0x61, 0x67, 0x65, 0x2f, 0x2a, 0x3b, 0x71, 0x3d, 
    0x30, 0x2e, 0x38, 0x2c, 0x2a, 0x2f, 0x2a, 0x3b,
    0x71, 0x3d, 0x30, 0x2e, 0x35, 0x0d, 0x0a, 0x41, 
    0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x4c, 0x61,
    0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x3a, 0x20, 
    0x65, 0x6e, 0x2d, 0x75, 0x73, 0x2c, 0x65, 0x6e,
    0x3b, 0x71, 0x3d, 0x30, 0x2e, 0x35, 0x0d, 0x0a, 
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d,
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x3a, 
    0x20, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d,
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x0d, 0x0a, 0x41, 
    0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x43, 0x68,
    0x61, 0x72, 0x73, 0x65, 0x74, 0x3a, 0x20, 0x49, 
    0x53, 0x4f, 0x2d, 0x38, 0x38, 0x35, 0x39, 0x2d,
    0x31, 0x2c, 0x75, 0x74, 0x66, 0x2d, 0x38, 0x3b, 
    0x71, 0x3d, 0x30, 0x2e, 0x37, 0x2c, 0x2a, 0x3b,
    0x71, 0x3d, 0x30, 0x2e, 0x37, 0x0d, 0x0a, 0x4b, 
    0x65, 0x65, 0x70, 0x2d, 0x41, 0x6c, 0x69, 0x76,
    0x65, 0x3a, 0x20, 0x33, 0x30, 0x30, 0x0d, 0x0a, 
    0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
    0x6f, 0x6e, 0x3a, 0x20, 0x6b, 0x65, 0x65, 0x70, 
    0x2d, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x0d, 0x0a,
    0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x3a, 
    0x20, 0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f,
    0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x6d, 0x79, 0x73, 
    0x70, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
    0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 
    0x66, 0x6d, 0x3f, 0x66, 0x75, 0x73, 0x65, 0x61,
    0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3d, 0x75, 0x73, 
    0x65, 0x72, 0x0d, 0x0a, 0x43, 0x6f, 0x6f, 0x6b,
    0x69, 0x65, 0x3a, 0x20, 0x4d, 0x53, 0x43, 0x75, 
    0x6c, 0x74, 0x75, 0x72, 0x65, 0x3d, 0x49, 0x50,
    0x3d, 0x31, 0x34, 0x30, 0x2e, 0x32, 0x32, 0x31, 
    0x2e, 0x32, 0x33, 0x38, 0x2e, 0x32, 0x35, 0x30,
    0x26, 0x49, 0x50, 0x43, 0x75, 0x6c, 0x74, 0x75, 
    0x72, 0x65, 0x3d, 0x65, 0x6e, 0x2d, 0x55, 0x53,
    0x26, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 
    0x65, 0x64, 0x43, 0x75, 0x6c, 0x74, 0x75, 0x72,
    0x65, 0x3d, 0x65, 0x6e, 0x2d, 0x55, 0x53, 0x26, 
    0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65,
    0x64, 0x43, 0x75, 0x6c, 0x74, 0x75, 0x72, 0x65, 
    0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3d,
    0x26, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 
    0x3d, 0x56, 0x56, 0x4d, 0x3d, 0x26, 0x46, 0x6f,
    0x72, 0x63, 0x65, 0x64, 0x45, 0x78, 0x70, 0x69, 
    0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3d, 0x30,
    0x26, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 
    0x65, 0x3d, 0x30, 0x26, 0x55, 0x53, 0x52, 0x4c,
    0x4f, 0x43, 0x3d, 0x51, 0x58, 0x4a, 0x6c, 0x59, 
    0x55, 0x4e, 0x76, 0x5a, 0x47, 0x55, 0x39, 0x4e,
    0x6a, 0x4d, 0x77, 0x4a, 0x6b, 0x4e, 0x70, 0x64, 
    0x48, 0x6b, 0x39, 0x54, 0x47, 0x56, 0x74, 0x62,
    0x32, 0x35, 0x30, 0x4a, 0x6b, 0x4e, 0x76, 0x64, 
    0x57, 0x35, 0x30, 0x63, 0x6e, 0x6c, 0x44, 0x62,
    0x32, 0x52, 0x6c, 0x50, 0x56, 0x56, 0x54, 0x4a, 
    0x6b, 0x4e, 0x76, 0x64, 0x57, 0x35, 0x30, 0x63,
    0x6e, 0x6c, 0x4f, 0x59, 0x57, 0x31, 0x6c, 0x50, 
    0x56, 0x56, 0x75, 0x61, 0x58, 0x52, 0x6c, 0x5a,
    0x43, 0x42, 0x54, 0x64, 0x47, 0x46, 0x30, 0x5a, 
    0x58, 0x4d, 0x6d, 0x52, 0x47, 0x31, 0x68, 0x51,
    0x32, 0x39, 0x6b, 0x5a, 0x54, 0x30, 0x32, 0x4d, 
    0x44, 0x49, 0x6d, 0x54, 0x47, 0x46, 0x30, 0x61,
    0x58, 0x52, 0x31, 0x5a, 0x47, 0x55, 0x39, 0x4e, 
    0x44, 0x45, 0x75, 0x4e, 0x6a, 0x67, 0x78, 0x4e,
    0x53, 0x5a, 0x4d, 0x62, 0x32, 0x35, 0x6e, 0x61, 
    0x58, 0x52, 0x31, 0x5a, 0x47, 0x55, 0x39, 0x4c,
    0x54, 0x67, 0x33, 0x4c, 0x6a, 0x6b, 0x33, 0x4d, 
    0x44, 0x59, 0x6d, 0x55, 0x47, 0x39, 0x7a, 0x64,
    0x47, 0x46, 0x73, 0x51, 0x32, 0x39, 0x6b, 0x5a, 
    0x54, 0x30, 0x32, 0x4d, 0x44, 0x51, 0x7a, 0x4f,
    0x53, 0x5a, 0x53, 0x5a, 0x57, 0x64, 0x70, 0x62, 
    0x32, 0x35, 0x4f, 0x59, 0x57, 0x31, 0x6c, 0x50,
    0x55, 0x6c, 0x4d, 0x0d, 0x0a, 0x0d, 0x0a
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 839;
  packet_header.len        = 839;
  packet_header.ts.tv_sec  = 1226268299;
  packet_header.ts.tv_usec = 772389;
  packet->assign(&packet_header, data);

  return(packet);
}


#if 0
/*
######################################################################
#   Data exported from: Wireshark
#   Data for File:      VLAN_IP_UDP_DNS.txt
######################################################################
No.     Time                       Source                Destination           Protocol Info
  33603 2008-11-09 22:08:22.758106 140.221.251.250       68.142.196.63         DNS      Standard query A media.adrevolver.com
Frame 33603 (95 bytes on wire, 95 bytes captured)
    Arrival Time: Nov  9, 2008 22:08:22.758106000
    [Time delta from previous captured frame: 0.025159000 seconds]
    [Time delta from previous displayed frame: 0.362256000 seconds]
    [Time since reference or first frame: 246.720927000 seconds]
    Frame Number: 33603
    Frame Length: 95 bytes
    Capture Length: 95 bytes
    [Frame is marked: False]
    [Protocols in frame: eth:vlan:ip:udp:dns]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: JuniperN_92:48:7e (00:1d:b5:92:48:7e), Dst: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
    Destination: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        Address: JuniperN_75:e4:9d (00:90:69:75:e4:9d)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Source: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        Address: JuniperN_92:48:7e (00:1d:b5:92:48:7e)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Type: 802.1Q Virtual LAN (0x8100)
802.1Q Virtual LAN, PRI: 0, CFI: 0, ID: 521
    000. .... .... .... = Priority: 0
    ...0 .... .... .... = CFI: 0
    .... 0010 0000 1001 = ID: 521
    Type: IP (0x0800)
Internet Protocol, Src: 140.221.251.250 (140.221.251.250), Dst: 68.142.196.63 (68.142.196.63)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00)
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..0. = ECN-Capable Transport (ECT): 0
        .... ...0 = ECN-CE: 0
    Total Length: 77
    Identification: 0xf6a2 (63138)
    Flags: 0x00
        0... = Reserved bit: Not set
        .0.. = Don't fragment: Not set
        ..0. = More fragments: Not set
    Fragment offset: 0
    Time to live: 62
    Protocol: UDP (0x11)
    Header checksum: 0xf457 [correct]
        [Good: True]
        [Bad : False]
    Source: 140.221.251.250 (140.221.251.250)
    Destination: 68.142.196.63 (68.142.196.63)
User Datagram Protocol, Src Port: 5609 (5609), Dst Port: domain (53)
    Source port: 5609 (5609)
    Destination port: domain (53)
    Length: 57
    Checksum: 0x1491 [correct]
        [Good Checksum: True]
        [Bad Checksum: False]
Domain Name System (query)
    [Response In: 33604]
    Transaction ID: 0x48d1
    Flags: 0x0000 (Standard query)
        0... .... .... .... = Response: Message is a query
        .000 0... .... .... = Opcode: Standard query (0)
        .... ..0. .... .... = Truncated: Message is not truncated
        .... ...0 .... .... = Recursion desired: Don't do query recursively
        .... .... .0.. .... = Z: reserved (0)
        .... .... ...0 .... = Non-authenticated data OK: Non-authenticated data is unacceptable
    Questions: 1
    Answer RRs: 0
    Authority RRs: 0
    Additional RRs: 1
    Queries
        media.adrevolver.com: type A, class IN
            Name: media.adrevolver.com
            Type: A (Host address)
            Class: IN (0x0001)
    Additional records
        <Root>: type OPT
            Name: <Root>
            Type: OPT (EDNS0 option)
            UDP payload size: 4096
            Higher bits in extended RCODE: 0x0
            EDNS0 version: 0
            Z: 0x8000
                Bit 0 (DO bit): 1 (Accepts DNSSEC security RRs)
                Bits 1-15: 0x0 (reserved)
            Data length: 0
######################################################################
*/
#endif

string get_VLAN_IP_UDP_DNS_str(void)
{
  string VLAN_IP_UDP_DNS_str = "0,site-name,1226268502.758106,0.000000,521,17,140.221.251.250,68.142.196.63,,,49,,95,,1,,,,5609,53,,,,,,,,,,,,,,,,,,,,,,,,,,,C,,";

  return(VLAN_IP_UDP_DNS_str);
}


sharedPacket get_VLAN_IP_UDP_DNS_pkt(void)
{
  string ts("2008-11-09 22:08:22.758106");
  ptime  pt(time_from_string(ts));
  time_duration diff = pt - getEpochUTC();

  static char unsigned data[95] = 
  {
    0x00, 0x90, 0x69, 0x75, 0xe4, 0x9d, 0x00, 0x1d, 
    0xb5, 0x92, 0x48, 0x7e, 0x81, 0x00, 0x02, 0x09,
    0x08, 0x00, 0x45, 0x00, 0x00, 0x4d, 0xf6, 0xa2, 
    0x00, 0x00, 0x3e, 0x11, 0xf4, 0x57, 0x8c, 0xdd,
    0xfb, 0xfa, 0x44, 0x8e, 0xc4, 0x3f, 0x15, 0xe9, 
    0x00, 0x35, 0x00, 0x39, 0x14, 0x91, 0x48, 0xd1,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x01, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61,
    0x0a, 0x61, 0x64, 0x72, 0x65, 0x76, 0x6f, 0x6c, 
    0x76, 0x65, 0x72, 0x03, 0x63, 0x6f, 0x6d, 0x00,
    0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x29, 0x10, 
    0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00
  };

  sharedPacket packet(new Packet(false));
  struct pcap_pkthdr packet_header;
  packet_header.caplen     = 95;
  packet_header.len        = 95;
  packet_header.ts.tv_sec  = 1226268502;
  packet_header.ts.tv_usec = 758106;
  packet->assign(&packet_header, data);

  return(packet);
}


map<string, Pair<string, sharedPacket> > getPacketMap(void)
{
  map<string, Pair<string, sharedPacket> > packet_map;
  Pair<string, sharedPacket> A(get_IPV6_ICMPV6_str(), get_IPV6_ICMPV6_pkt(), true);
  packet_map.insert(make_pair("IPV6_ICMPV6", A));
  Pair<string, sharedPacket> B(get_IPV6_TCP_HTTP_truncated_str(), get_IPV6_TCP_HTTP_truncated_pkt(), true);
  packet_map.insert(make_pair("IPV6_TCP_HTTP_truncated", B));
  Pair<string, sharedPacket> C(get_IPV6_UDP_truncated_str(), get_IPV6_UDP_truncated_pkt(), true);
  packet_map.insert(make_pair("IPV6_UDP_truncated", C));
  Pair<string, sharedPacket> D(get_IP_ICMP_UDP_unreachable_str(), get_IP_ICMP_UDP_unreachable_pkt(), true);
  packet_map.insert(make_pair("IP_ICMP_UDP_unreachable", D));
  Pair<string, sharedPacket> E(get_IP_ICMP_ping_str(), get_IP_ICMP_ping_pkt(), true);
  packet_map.insert(make_pair("IP_ICMP_ping", E));
  Pair<string, sharedPacket> F(get_IP_IGMP_str(), get_IP_IGMP_pkt(), true);
  packet_map.insert(make_pair("IP_IGMP", F));
  Pair<string, sharedPacket> G(get_IP_TCP_HTTP_str(), get_IP_TCP_HTTP_pkt(), true);
  packet_map.insert(make_pair("IP_TCP_HTTP", G));
  Pair<string, sharedPacket> H(get_IP_UDP_DNS_str(), get_IP_UDP_DNS_pkt(), true);
  packet_map.insert(make_pair("IP_UDP_DNS", H));
  Pair<string, sharedPacket> I(get_VLAN_IP_ICMP_UDP_unreachable_str(), get_VLAN_IP_ICMP_UDP_unreachable_pkt(), true);
  packet_map.insert(make_pair("VLAN_IP_ICMP_UDP_unreachable", I));
  Pair<string, sharedPacket> J(get_VLAN_IP_ICMP_ping_str(), get_VLAN_IP_ICMP_ping_pkt(), true);
  packet_map.insert(make_pair("VLAN_IP_ICMP_ping", J));
  Pair<string, sharedPacket> K(get_VLAN_IP_IGMP_str(), get_VLAN_IP_IGMP_pkt(), true);
  packet_map.insert(make_pair("VLAN_IP_IGMP", K));
  Pair<string, sharedPacket> L(get_VLAN_IP_TCP_HTTP_str(), get_VLAN_IP_TCP_HTTP_pkt(), true);
  packet_map.insert(make_pair("VLAN_IP_TCP_HTTP", L));
  Pair<string, sharedPacket> M(get_VLAN_IP_UDP_DNS_str(), get_VLAN_IP_UDP_DNS_pkt(), true);
  packet_map.insert(make_pair("VLAN_IP_UDP_DNS", M));

  return(packet_map);
}


#endif
